language: java

sudo: false

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk8

#branches:
#  only:
#    - master
install: mvn install

notifications:
  email:
    recipients:
    - juraj.somorovsky@hackmanit.de
    - robert.merget@rub.de
