language: java

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

#branches:
#  only:
#    - master

notifications:
  email:
    recipients:
    - juraj.somorovsky@hackmanit.de
    - robert.merget@rub.de